### PR TITLE
Fix #56 parse more often

### LINKED ISSUE #56: Parse more often
An FSAC parse should be performed on every edit. To be pragmatic about it, it should probably be done after an edit, and being idle for x msecs. As it is now, you have to invoke completions just to get errors to update. Not ideal. 

Call parse on edit (possibly with delay) 
Call parse on view change (every time)

### PR DESCRIPTION
**Pull request by guillermooo**

### CODE REVIEW

**Comment by rojepp** [comment]
Maybe I'm missing something, but it looks like IdleParser is never constructed?

We shouldn't reparse if nothing has changed since the last parse?

**Comment by guillermooo** [comment]
Instantiating plugin classes is the job of the plugin loader. Some plugins are instantiated per-view, some per-window, others per-application.

**Comment by guillermooo** [comment]
> We shouldn't reparse if nothing has changed since the last parse?

Makes sense. Will fix.

**Comment by rojepp** [comment]
Ah, so sublime provides IdleIntervalEventListener?

**Comment by guillermooo** [comment]
https://github.com/fsharp/sublime-fsharp-package/blob/master/FSharp/sublime_plugin_lib/events.py#L9

**Comment by rojepp** [comment]
Thanks for explaining.

**Pull request merged**
